(()=>{
const $=id=>document.getElementById(id);
const DEFAULT=['Sala','Comedor','Cocina','Kitchenette','Dormitorio principal','Dormitorio','Baño principal','Baño','Baño social','Cochera','Estudio','Lavandería','Patio','Jardín','Terraza','Sala de TV','Walk-in closet','Tienda / comercio','Depósito','Gimnasio','Balcón','Zona de parrilla','Otro'];
const KEY='vismoInterviewRoomTemplatesV17', SAVE='vismoInterviewSavedV17';
let templates=JSON.parse(localStorage.getItem(KEY)||'null')||DEFAULT.slice();
let state={floors:[]};
const floorName=i=>i===0?'Primer piso':i===1?'Segundo piso':i===2?'Tercer piso':`${i+1}.° piso`;
const esc=s=>String(s??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
function ensure(){if(!state.floors.length){let n=Math.max(1,+$('iLevels').value||1);for(let i=0;i<n;i++)state.floors.push({name:floorName(i),rooms:[]});}}
function renderTemplates(){let box=$('roomTemplateList');if(!box)return;box.innerHTML=templates.map((x,i)=>`<label style="display:flex;gap:8px;align-items:center"><input data-i="${i}" class="tplName" value="${esc(x)}"><button type="button" class="btn tiny tplDel" data-i="${i}">Quitar</button></label>`).join('');box.querySelectorAll('.tplName').forEach(x=>x.addEventListener('change',()=>{templates[+x.dataset.i]=x.value.trim()||templates[+x.dataset.i];persistTemplates();renderFloors()}));box.querySelectorAll('.tplDel').forEach(x=>x.addEventListener('click',()=>{templates.splice(+x.dataset.i,1);persistTemplates();renderTemplates();renderFloors()}))}
function persistTemplates(){localStorage.setItem(KEY,JSON.stringify(templates))}
function renderFloors(){ensure();let box=$('floors');if(!box)return;box.innerHTML=state.floors.map((f,fi)=>`<div class="floorCard"><div class="floorHead"><input class="floorNameV17" data-fi="${fi}" value="${esc(f.name)}"><button class="btn tiny delFloorV17" data-fi="${fi}" type="button">Eliminar piso</button></div><div class="roomQuick">${templates.map((r,ri)=>`<button type="button" class="addRoomV17" data-fi="${fi}" data-ri="${ri}">＋ ${esc(r)}</button>`).join('')}</div><div class="roomList">${f.rooms.map((r,ri)=>`<div class="roomChip needed"><b>${esc(r)}</b> <button type="button" class="removeRoomV17" data-fi="${fi}" data-ri="${ri}">×</button></div>`).join('')||'<span class="hint">Aún no hay ambientes en este piso.</span>'}</div></div>`).join('');
box.querySelectorAll('.floorNameV17').forEach(x=>x.addEventListener('change',()=>state.floors[+x.dataset.fi].name=x.value));
box.querySelectorAll('.delFloorV17').forEach(x=>x.addEventListener('click',()=>{state.floors.splice(+x.dataset.fi,1);renderFloors();updateDiagram()}));
box.querySelectorAll('.addRoomV17').forEach(x=>x.addEventListener('click',()=>{let fi=+x.dataset.fi,r=templates[+x.dataset.ri];state.floors[fi].rooms.push(r);renderFloors();updateDiagram()}));
box.querySelectorAll('.removeRoomV17').forEach(x=>x.addEventListener('click',()=>{state.floors[+x.dataset.fi].rooms.splice(+x.dataset.ri,1);renderFloors();updateDiagram()}));
}
function collect(){return{fecha:new Date().toLocaleString('es-PE'),client:$('iClient').value,site:$('iSite').value,area:$('iArea').value,levels:$('iLevels').value,fronts:$('iFronts').value,people:$('people').value,vehicles:$('vehicles').value,pets:$('pets').value,priorities:[$('priority1').value,$('priority2').value,$('priority3').value],stylePref:$('stylePref').value,facadeCode:$('facadeCode').value,reference:$('reference').value,floors:state.floors}}
function updateDiagram(){ensure();let d=$('diagram');if(!d)return;d.innerHTML=state.floors.map(f=>`<div class="diagramFloor"><h3>${esc(f.name)}</h3><div class="bubbles">${f.rooms.map(r=>`<div class="bubble needed"><b>${esc(r)}</b></div>`).join('')||'<span class="hint">Sin ambientes todavía</span>'}</div></div>`).join('');let total=state.floors.reduce((a,f)=>a+f.rooms.length,0),w=[];if(total>=15)w.push('Se han solicitado numerosos ambientes. VISMO revisará dimensiones y prioridades.');$('designWarnings').innerHTML=w.map(x=>`<div class="softWarn">${x}</div>`).join('')}
function save(){let d=collect();localStorage.setItem(SAVE,JSON.stringify(d));let all=JSON.parse(localStorage.getItem('vismo_requerimientos')||'[]');all.unshift({id:'REQ-'+Date.now(),fecha:d.fecha,nombre:d.client,predio:{area:d.area},pisos:d.levels,floors:d.floors,origen:'Entrevista interna VISMO'});localStorage.setItem('vismo_requerimientos',JSON.stringify(all));alert('Entrevista guardada correctamente en VISMO.')}
function exportFicha(){let d=collect(),floors=d.floors.map(f=>`<h3>${esc(f.name)}</h3><p>${f.rooms.length?f.rooms.map(esc).join(' · '):'Sin ambientes registrados'}</p>`).join('');let w=window.open('','_blank');if(!w){alert('El navegador bloqueó la ficha. Permite ventanas emergentes para imprimirla.');return}w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>Ficha VISMO</title><style>body{font-family:Arial;max-width:800px;margin:32px auto;color:#171717;font-size:12px;line-height:1.35}h1{font-family:Georgia;font-size:25px;margin:0 0 18px}h2{font-size:17px;border-bottom:1px solid #b58a3b;padding-bottom:6px;margin:16px 0 10px}h3{font-size:13px;margin:11px 0 4px}p{margin:4px 0}.meta{display:grid;grid-template-columns:1fr 1fr;gap:6px 18px}.box{border:1px solid #ddd;padding:14px;margin:10px 0}@media print{@page{size:A4;margin:15mm}body{margin:0;font-size:10.5pt}h1{font-size:20pt}h2{font-size:13pt}h3{font-size:11pt}button{display:none}}</style></head><body><h1>VISMO · Entrevista de diseño</h1><div class="meta"><p><b>Cliente:</b> ${esc(d.client)}</p><p><b>Proyecto:</b> ${esc(d.site)}</p><p><b>Área:</b> ${esc(d.area)} m²</p><p><b>Pisos:</b> ${esc(d.levels)}</p></div><h2>Requerimientos por piso</h2>${floors}<h2>Preferencias</h2><p><b>Prioridades:</b> ${d.priorities.filter(Boolean).map(esc).join(' · ')||'—'}</p><p><b>Estilo:</b> ${esc(d.stylePref)||'—'}</p><p><b>Fachada:</b> ${esc(d.facadeCode)||'—'}</p><button onclick="print()">Imprimir / Guardar PDF</button></body></html>`);w.document.close()}
$('addFloor')?.addEventListener('click',e=>{e.stopImmediatePropagation();state.floors.push({name:floorName(state.floors.length),rooms:[]});$('iLevels').value=state.floors.length;renderFloors();updateDiagram()},true);
$('refreshDiagram')?.addEventListener('click',e=>{e.stopImmediatePropagation();updateDiagram()},true);
$('saveInterview')?.addEventListener('click',e=>{e.stopImmediatePropagation();save()},true);
$('exportInterview')?.addEventListener('click',e=>{e.stopImmediatePropagation();exportFicha()},true);
$('addRoomTemplate')?.addEventListener('click',()=>{let v=$('newRoomTemplate').value.trim();if(!v)return;templates.push(v);$('newRoomTemplate').value='';persistTemplates();renderTemplates();renderFloors()});
$('resetRoomTemplates')?.addEventListener('click',()=>{templates=DEFAULT.slice();persistTemplates();renderTemplates();renderFloors()});
$('iLevels')?.addEventListener('change',()=>{let n=Math.max(1,+$('iLevels').value||1);while(state.floors.length<n)state.floors.push({name:floorName(state.floors.length),rooms:[]});while(state.floors.length>n)state.floors.pop();renderFloors();updateDiagram()});
renderTemplates();ensure();renderFloors();updateDiagram();
})();
