(()=>{
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
// V21 — ejecución de obra estructurada
const panel=$('workBudgetPanel');
if(panel){panel.innerHTML=`<h2>05 · PRESUPUESTO DE OBRA</h2><p class="hint">Para contratos de ejecución. Puedes crear cuadros independientes por piso, etapa o tipo de presupuesto.</p><div id="budgetSections"></div><div class="actions"><button type="button" class="btn" id="addBudgetSection">＋ Agregar cuadro</button></div>`;}
function rowHTML(x={}){return `<div class="budgetrow v21row"><input class="bdesc" placeholder="Partida / material" value="${esc(x.desc||'')}"><select class="bunit">${['Und','m²','ml','m³','kg','Bls','Var','Mill','Volq','Glb','Mes'].map(u=>`<option ${x.unit===u?'selected':''}>${u}</option>`).join('')}</select><input class="bqty" type="number" step=".01" placeholder="Metrado" value="${x.qty??''}"><input class="bpu" type="number" step=".01" placeholder="P. unit. S/" value="${x.pu??''}"><input class="btotal" type="number" step=".01" placeholder="Total S/" value="${x.total??''}"><button type="button" class="btn v21del">×</button></div>`}
function addSection(s={title:'1° PISO',kind:'Materiales',rows:[]}){let d=document.createElement('div');d.className='panel budgetSection';d.innerHTML=`<div class="grid"><label>Título del cuadro<input class="bsTitle" value="${esc(s.title)}"></label><label>Tipo<select class="bsKind"><option>Materiales</option><option>Mano de obra</option><option>Materiales + mano de obra</option><option>Otro</option></select></label></div><div class="bsRows"></div><div class="actions"><button type="button" class="btn bsAdd">＋ Agregar fila</button><button type="button" class="btn bsRemove">Eliminar cuadro</button></div>`;d.querySelector('.bsKind').value=s.kind||'Materiales';$('budgetSections').appendChild(d);let rows=d.querySelector('.bsRows');(s.rows?.length?s.rows:[{}]).forEach(x=>rows.insertAdjacentHTML('beforeend',rowHTML(x)));d.querySelector('.bsAdd').onclick=()=>rows.insertAdjacentHTML('beforeend',rowHTML());d.querySelector('.bsRemove').onclick=()=>d.remove();d.addEventListener('click',e=>{if(e.target.classList.contains('v21del'))e.target.parentElement.remove()});d.addEventListener('input',e=>{if(e.target.classList.contains('bqty')||e.target.classList.contains('bpu')){let r=e.target.closest('.v21row'),q=+r.querySelector('.bqty').value||0,p=+r.querySelector('.bpu').value||0;r.querySelector('.btotal').value=(q*p).toFixed(2)}})}
$('addBudgetSection')?.addEventListener('click',()=>addSection({title:`${document.querySelectorAll('.budgetSection').length+1}° PISO`,kind:'Materiales'})); if($('budgetSections')) addSection();
const oldData=window.data; if(typeof oldData==='function'){window.data=function(){let d=oldData();d.budgetSections=[...document.querySelectorAll('.budgetSection')].map(s=>({title:s.querySelector('.bsTitle').value.trim(),kind:s.querySelector('.bsKind').value,rows:[...s.querySelectorAll('.v21row')].map(r=>({desc:r.querySelector('.bdesc').value.trim(),unit:r.querySelector('.bunit').value,qty:+r.querySelector('.bqty').value||0,pu:+r.querySelector('.bpu').value||0,total:+r.querySelector('.btotal').value||0})).filter(r=>r.desc)})).filter(s=>s.title&&s.rows.length);return d}}
function money(n){return 'S/ '+(+n||0).toLocaleString('es-PE',{minimumFractionDigits:2,maximumFractionDigits:2})}
function table(s){let total=s.rows.reduce((a,r)=>a+(+r.total||(+r.qty||0)*(+r.pu||0)),0);return `<h3 class="budgetTitle">${esc(s.title)} · ${esc(s.kind)}</h3><table class="contractBudget"><thead><tr><th>PARTIDA / MATERIAL</th><th>UNIDAD</th><th>METRADO</th><th>P. U.</th><th>TOTAL</th></tr></thead><tbody>${s.rows.map(r=>`<tr><td>${esc(r.desc)}</td><td>${esc(r.unit)}</td><td>${r.qty}</td><td>${money(r.pu)}</td><td>${money(r.total||r.qty*r.pu)}</td></tr>`).join('')}<tr><td colspan="4"><b>TOTAL ${esc(s.title)}</b></td><td><b>${money(total)}</b></td></tr></tbody></table>`}
const oldBODY=window.BODY;if(typeof oldBODY==='function'){window.BODY=function(d){if(!['Construcción','Obra a todo costo'].includes(d.type))return oldBODY(d);let n=1,body=parties(d);body+=sec(n++,'OBJETO DEL CONTRATO',`<p>El presente contrato tiene por objeto la <b>ejecución de obra${d.workMode?' bajo la modalidad '+esc(d.workMode):''}</b> del proyecto ${esc(d.projectType||'')} ubicado en <b>${esc(d.site||'la ubicación indicada')}</b>, conforme a los planos, alcances y condiciones pactadas.</p>`);body+=sec(n++,'ESPECIFICACIONES TÉCNICAS Y ALCANCE DE LA EJECUCIÓN',`<p>La ejecución comprende las siguientes partidas y trabajos:</p>${ul(d.scope||[])}${d.notes?`<p><b>Precisiones adicionales:</b> ${esc(d.notes).replace(/\n/g,'<br>')}</p>`:''}${d.workExclusions?`<p><b>Exclusiones / precisiones:</b> ${esc(d.workExclusions)}</p>`:''}`);if(d.budgetSections?.length)body+=sec(n++,'PRESUPUESTO DE MATERIALES Y MANO DE OBRA',`<p>Los cuadros siguientes forman parte integrante del presente contrato.</p>${d.budgetSections.map(table).join('')}`);body+=sec(n++,'DISPOSICIONES GENERALES',`<p>La obra será ejecutada de acuerdo con los planos, especificaciones y alcances expresamente incorporados al presente contrato. El cuidado de materiales, herramientas, seguridad del personal, servicios provisionales y demás obligaciones se regirá por lo indicado en el alcance contratado y por las cláusulas adicionales que las partes incorporen.</p>`);body+=sec(n++,'INICIO Y PLAZO DE EJECUCIÓN',`<p>La fecha de inicio será <b>${esc(d.start||'por definir')}</b>. El plazo de ejecución será el que las partes establezcan para el proyecto y podrá precisarse mediante cláusula adicional.</p>`);body+=sec(n++,'MONTO DEL CONTRATO',`<p>El monto contractual asciende a <b>${money(d.amount)}</b>. ${d.igv==='Agregar 18%'?'Al monto indicado se agregará el IGV correspondiente.':d.igv==='Incluido'?'El monto contractual incluye IGV.':'<b>El monto contractual no incluye IGV.</b>'}</p>`);body+=sec(n++,'FORMA DE PAGO',pays(d));if(Array.isArray(d.customClauses))d.customClauses.forEach(c=>{if(c?.content)body+=sec(n++,c.title||'CONDICIÓN ESPECIAL',`<p>${esc(c.content).replace(/\n/g,'<br>')}</p>`)});body+=sec(n++,'CONFORMIDAD',`<p>En señal de conformidad, ambas partes suscriben el presente contrato por duplicado.</p>`);return body}}
// Modelo maestro separado para ejecución de obra
const KEY='vismoProyectosV6ContractModels';try{let a=JSON.parse(localStorage.getItem(KEY)||'[]');if(!a.some(x=>x.v21Execution)){a.push({name:'Ejecución de obra · A todo costo',type:'Obra a todo costo',v21Execution:true,body:'Modelo estructurado para ejecución física de obra. Incluye objeto, especificaciones técnicas, cuadros de presupuesto por piso/etapa, disposiciones generales, plazo, monto, cuotas variables, conformidad y adelantos.',updatedAt:new Date().toISOString()});localStorage.setItem(KEY,JSON.stringify(a));setTimeout(()=>window.renderModels?.(),50)}}catch(e){}
// Al usar el modelo de ejecución, NO enviarlo a Alcances adicionales.
document.addEventListener('click',e=>{let b=e.target.closest?.('[data-v21-exec]');if(!b)return},true);
// Mejoras visuales para tablas del contrato
let st=document.createElement('style');st.textContent=`.v21row{grid-template-columns:2fr .7fr .8fr .9fr .9fr auto}.contractBudget{width:100%;border-collapse:collapse;margin:12px 0 24px}.contractBudget th,.contractBudget td{border:1px solid #aaa;padding:6px;font-size:11px}.contractBudget th{background:#f1ede6}.budgetTitle{margin:18px 0 6px;font-size:14px}@media(max-width:800px){.v21row{grid-template-columns:1fr 1fr}}`;document.head.appendChild(st);
})();
